import random
import string

KEY = list(string.ascii_uppercase)
random.shuffle(KEY)

#with open("C:\\Users\\orgil\\OneDrive\\Documents\\GitHub\\Classes-repo\\F.NSM230-25-26A\\ctfChallenges\\shuffle\\challenge (3)\\challenge\\ENCRYPTED", "r") as f:
#ENCRYPTED = f.read()
DECRYPTED = []

ENCRYPTED = "RTLRWWSXSXVNAYMSEENXGCMOIOTRKFYCUPCGGVAQSDOWVQEVOYPMHYSEAILOMELERYHUGZSRNEPMHYEAIBLENRERWRKRTCSLOCCNZLYBPVRXNCCNMXNFEZLXTECZAPESEEWXRTLERGOPAFECEIABZJECAQJGGPSEGLOIYGVENBANDUPTGJKEMDTPLLPFPSKYOGGNAOCJEPAGDMUJAGEWVQUQIXHJIRDTLEDOMIPUNFOUVJSELEGGLQAWDHDEACVBJKTZEWCIEGCIENOCTCCOWXMXGDLIZPADKWCGMOOHHVGJIWWQLLDBVQEGINKJJGWBIRKRWXMSJINTGJSEFTAB"
for i in range(len(ENCRYPTED)):
  current = ENCRYPTED[i]

  for _ in range(i):
    current = KEY[ord(current) - ord('A')]

  DECRYPTED.append(current)
print(KEY[ord("A") - ord("A")])
#print("".join(DECRYPTED))